### ISSUE TITLE
大佬能给个mihomotproxy的op配置文件吗  

### ISSUE THREAD

**Issue by 77160860** [refined-fish/clash_rule_fish#1]
我直接替换进去试试

**Comment by 77160860** [comment]
time="2024-12-10T14:47:31.910442029+08:00" level=warning msg="can't download  file: Get \"https://ghp.ci/github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip\": EOF"

**Comment by refined-fish** [comment]
> 大佬能给个mihomotproxy的op配置文件吗

mihomo的文档都有贴出配置文件示例，你可以直接复制然后修改你需要的部分，我没有做模板，是根据我的使用环境手搓的，不适合其他人

**Comment by refined-fish** [comment]
> time="2024-12-10T14:47:31.910442029+08:00" level=warning msg="can't download file: Get "[https://ghp.ci/github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip\](https://ghp.ci/github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip%5C)": EOF"

日志类型换成debug，内核才会给出详细的失败原因，看看是DNS失败没有获取到IP无法连接，还是获取到了IP但是连接不上，ghp.ci这个加速，有时候有的地区可能被屏蔽打不开

**Comment by refined-fish** [comment]
我去掉不适合其他人使用的部分，还是做了一个模板，你可以到[主页](https://github.com/refined-fish/clash_rule_fish?tab=readme-ov-file#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E6%A8%A1%E6%9D%BF)查看

**Comment by 77160860** [comment]
> 我去掉不适合其他人使用的部分，还是做了一个模板，你可以到[主页](https://github.com/refined-fish/clash_rule_fish?tab=readme-ov-file#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E6%A8%A1%E6%9D%BF)查看

yaml文件直接用你那个 ， 那个/etc/config/mihomo 这个设置文件能提供个吗  ？

**Comment by refined-fish** [comment]
> > 我去掉不适合其他人使用的部分，还是做了一个模板，你可以到[主页](https://github.com/refined-fish/clash_rule_fish?tab=readme-ov-file#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E6%A8%A1%E6%9D%BF)查看
> 
> yaml文件直接用你那个 ， 那个/etc/config/mihomo 这个设置文件能提供个吗 ？

这是个mihomo的配置文件仓库，你应该去openWRT-mihomoTproxy提问
