### ISSUE TITLE
YAML语法层面规范

### ISSUE THREAD

**Issue by flairvibe** [refined-fish/clash_rule_fish#4]
use-all-proxy-providers: &use-all-proxy-providers
  use:
    provider1（不加-好像不规范，可能存在兼容性问题，通不过配置测试）
use:
    - provider1（改成这样就可以了）

**Comment by refined-fish** [comment]
确实，少了一个 - ，感谢抓虫，因为我自己是反向代理自动替换使用的所以没发现
